### ISSUE TITLE
Broken aiohttp install on python 3.10 when installing dependencies

### ISSUE THREAD

**Issue by AmozPay** [aleph-im/aleph-client#117]
Running into [this](https://github.com/aio-libs/aiohttp/issues/6898) very issue when installing `aleph-client` with `setup.py` on Python 3.10

Solution: upgrade requirement from `aiohttp>=3.8.0` to `aiohttp>=3.8.1`

"The most stable version is (and might be for a while) 3.8.1. I recommend you switch to it, as it will most likely have all the functionality you need, newest bugfixes and work out of the box." - See [here](https://github.com/aio-libs/aiohttp/issues/6898#issuecomment-1231532697)

**Comment by MHHukiewitz** [comment]
Fixed with #121
