### ISSUE TITLE
Protect users from executing an Aleph CLI command in a bad scope

### ISSUE THREAD

**Issue by aliel** [aleph-im/aleph-client#118]
When using the aleph program command for the first time without the private-key parameter a device.key file is automatically generated,
this can be a problem when commands are executed from the working directory.

eg:
```
aleph program . app:main
```
the behavior here is that we will deploy the program from the current directory and the device.key file

Proposed solution:

Read a gitignore if it exists and apply the rules.
check if a .git directory exists and exclude this directory
check if a device.key file exists and exclude this file
...
or print a message at the prompt and interactively ask the user to confirm the action.

**Comment by hoh** [comment]
#119 should solve the `device.key` issue.

Reading the `.gitignore` file could create issues since committed files should be uploaded in many cases (non compiled/minified languages).

Should we add a `.alephignore` file and let users decide if they want to symlink it to `.gitignore` ?

**Comment by aliel** [comment]
> Should we add a .alephignore file and let users decide if they want to symlink it to .gitignore ?
Good idea
