### ISSUE TITLE
Cannot create an instance with a disk of 5000 MB

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-client#238]
Version `0.7.1-rc1-1-g728bad9`

```
Maximum memory allocation on vm in MiB  (2048): 
Disk size in MiB  (20000): 5000 
Invalid input: 5000
Try again.
```

**Comment by philogicae** [comment]
Min allowed value is now 10240 [here](https://github.com/aleph-im/aleph-client/blob/35c3fc9b9f7af85f9388b3551762df7d41ddd866/src/aleph_client/commands/instance/__init__.py#L243)
