### ISSUE TITLE
Easy update (amend) of an aleph message

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-client#45]
It would be handy for users to have the ability to update an Aleph message easily.

A suggestion could be using the CLI:
`aleph amend 67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8`
-> opens the JSON in an editor with a ref to this id. Exiting properly would publish the message.

**Comment by MHHukiewitz** [comment]
Added in https://github.com/aleph-im/aleph-client/commit/0b17e096391f5f8cd2e958634536b4338d7d5f9c
