### ISSUE TITLE
Typo in query params name for get_posts and get_messages

### ISSUE THREAD

**Issue by geraldinefiser** [aleph-im/aleph-client#49]
While adding channels and time filtering on the JS SDK and looking at the pyaleph code I noticed this is probably a typo: 
params name should be **startDate** and **endDate** instead of start_date and end_date. 

This is used in both get_messages and get_posts functions. 

Let me know if you would like me to open a PR for it, or if it is easier for the team to fix it. 

https://github.com/aleph-im/aleph-client/blob/71dbab7b8107ea5676fbff5dc11d8418f77ac57b/src/aleph_client/asynchronous.py#L483

**Comment by hoh** [comment]
I checked [the relevant code in PyAleph](https://github.com/aleph-im/pyaleph/blob/26c1e30eff26909d0f4c6c07f0f4d799073588c4/src/aleph/web/controllers/utils.py#L71), and it appears to be the case. 

A PR would be welcome 🤗

**Comment by geraldinefiser** [comment]
I found the typo in the watch_messages function as well. 
Should be done! #50
