### ISSUE TITLE
Using storage_push_file results in 500

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/aleph-client#64]
Using the `storage_push_file(file_content, ...)` function results in a 500 complaining about missing the `filename` field in the form data. This field is not added by aleph-client and is required by the server.

It is not clear how an endpoint that allows the user to specify a filename fits with the Aleph storage model as we usually use hashes.

We should either:
* Compute the hash of the content and pass it as filename
* Deprecate the endpoint / unify it with the add_json endpoint.

**Comment by MHHukiewitz** [comment]
Doesn't seem to be the case anymore?
