### ISSUE TITLE
Choose between Pipfile and setup.cfg

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-client#76]
We do not use actively use the `Pipfile` and `Pipfile.lock` files at the moment, we use `setup.cfg` instead.

We should have only one way to define dependencies, either `setup.cfg` or `Pipfile`.

_Originally posted by @hoh in https://github.com/aleph-im/aleph-client/issues/72#issuecomment-1202375613_

**Comment by MHHukiewitz** [comment]
>/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

I guess we should use `Pipfile`.

**Comment by hoh** [comment]
Pipfile would be great for development and _containerized_ usage, but we may have to support other library versions based on what is distributed with supported Linux distributions and homebrew.

**Comment by mrhouzlane** [comment]
`We should have only one way to define dependencies, either setup.cfg or Pipfile.
`
- Pipefile is now working with python_version = "3.10" with all necessary packages but it is for development only. 
[Pipefile update packages](https://github.com/mrhouzlane/aleph-client/blob/pipefile-file/Pipfile)

**Comment by MHHukiewitz** [comment]
As I heard, setup.py does some stuff for us to upload the package to PyPI. Just to collect resources, here's some more info on packaging for PyPI: https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by odesenfans** [comment]
We use setup.cfg on all our projects. I have never used pipfile, but it seems to me like a classical case of "it ain't broke don't fix it". setup.cfg all the way for me.
